@echo off
echo Clearing build cache...
rmdir /s /q node_modules\.cache
echo Installing dependencies...
call npm install
echo Killing existing process on port 3002...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":3002" ^| find "LISTENING"') do taskkill /f /pid %%a
echo Starting development server...
npm start